// This file is generated by Scripts/vendor_languages.py.

import CRorkHighlighterParsers
import Foundation

/// Adds identifiers for languages distributed with the common parser pack.
extension LanguageID {
    /// Identifies the bundled Astro language.
    public static let astro: Self = "astro"

    /// Identifies the bundled Bash language.
    public static let bash: Self = "bash"

    /// Identifies the bundled C language.
    public static let c: Self = "c"

    /// Identifies the bundled C++ language.
    public static let cpp: Self = "cpp"

    /// Identifies the bundled CSS language.
    public static let css: Self = "css"

    /// Identifies the bundled Dockerfile language.
    public static let dockerfile: Self = "dockerfile"

    /// Identifies the bundled dotenv language.
    public static let dotenv: Self = "dotenv"

    /// Identifies the bundled Go language.
    public static let go: Self = "go"

    /// Identifies the bundled GraphQL language.
    public static let graphql: Self = "graphql"

    /// Identifies the bundled Groovy language.
    public static let groovy: Self = "groovy"

    /// Identifies the bundled HTML language.
    public static let html: Self = "html"

    /// Identifies the bundled Java language.
    public static let java: Self = "java"

    /// Identifies the bundled JavaScript language.
    public static let javascript: Self = "javascript"

    /// Identifies the bundled JSDoc language.
    public static let jsdoc: Self = "jsdoc"

    /// Identifies the bundled JSON language.
    public static let json: Self = "json"

    /// Identifies the bundled JSON5 language.
    public static let json5: Self = "json5"

    /// Identifies the bundled Kotlin language.
    public static let kotlin: Self = "kotlin"

    /// Identifies the bundled Markdown language.
    public static let markdown: Self = "markdown"

    /// Identifies the bundled Markdown Inline language.
    public static let markdownInline: Self = "markdown-inline"

    /// Identifies the bundled MDX language.
    public static let mdx: Self = "mdx"

    /// Identifies the bundled Objective-C language.
    public static let objectiveC: Self = "objective-c"

    /// Identifies the bundled Java Properties language.
    public static let properties: Self = "properties"

    /// Identifies the bundled Python language.
    public static let python: Self = "python"

    /// Identifies the bundled Regular Expression language.
    public static let regex: Self = "regex"

    /// Identifies the bundled Ruby language.
    public static let ruby: Self = "ruby"

    /// Identifies the bundled Rust language.
    public static let rust: Self = "rust"

    /// Identifies the bundled SCSS language.
    public static let scss: Self = "scss"

    /// Identifies the bundled SQL language.
    public static let sql: Self = "sql"

    /// Identifies the bundled Svelte language.
    public static let svelte: Self = "svelte"

    /// Identifies the bundled Swift language.
    public static let swift: Self = "swift"

    /// Identifies the bundled TOML language.
    public static let toml: Self = "toml"

    /// Identifies the bundled TSX language.
    public static let tsx: Self = "tsx"

    /// Identifies the bundled TypeScript language.
    public static let typescript: Self = "typescript"

    /// Identifies the bundled Vue language.
    public static let vue: Self = "vue"

    /// Identifies the bundled XML language.
    public static let xml: Self = "xml"

    /// Identifies the bundled YAML language.
    public static let yaml: Self = "yaml"

}

/// Builds catalogs from the parsers and queries bundled with the package.
extension LanguageCatalog {
    /// Creates the catalog bundled with the package.
    ///
    /// Parser pointers and compiled queries are initialized once per process
    /// and then reused by every standard catalog value.
    ///
    /// - Returns: A catalog containing every bundled language definition.
    /// - Throws: ``HighlighterError`` when a parser or resource is unavailable.
    public static func standard() throws(HighlighterError) -> Self {
        try standardCatalogResult.get()
    }

    /// Caches parser validation and query compilation for the process.
    private static let standardCatalogResult: Result<LanguageCatalog, HighlighterError> = {
        do {
            return .success(try makeStandardCatalog())
        } catch let error as HighlighterError {
            return .failure(error)
        } catch {
            return .failure(
                .bundledCatalogInitializationFailed(
                    message: String(describing: error)
                )
            )
        }
    }()

    /// Creates every bundled definition before the result is cached.
    ///
    /// - Returns: A validated language catalog.
    /// - Throws: ``HighlighterError`` when bundled metadata is invalid.
    private static func makeStandardCatalog() throws(HighlighterError) -> Self {
        let definitions: [BundledLanguageDefinition] = [
            BundledLanguageDefinition(
                id: .astro,
                displayName: "Astro",
                aliases: [],
                fileExtensions: ["astro"],
                filenames: [],
                treeSitterLanguage: tree_sitter_astro(),
                resourceDirectory: "astro",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .bash,
                displayName: "Bash",
                aliases: ["sh", "shell"],
                fileExtensions: ["bash", "bats", "sh", "zsh"],
                filenames: [".bash_profile", ".bashrc", ".profile", ".zprofile", ".zshrc"],
                treeSitterLanguage: tree_sitter_bash(),
                resourceDirectory: "bash",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .c,
                displayName: "C",
                aliases: [],
                fileExtensions: ["c", "h"],
                filenames: [],
                treeSitterLanguage: tree_sitter_c(),
                resourceDirectory: "c",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .cpp,
                displayName: "C++",
                aliases: ["c++", "cplusplus", "cxx"],
                fileExtensions: ["cc", "cpp", "cxx", "hh", "hpp", "hxx", "ipp", "tpp"],
                filenames: [],
                treeSitterLanguage: tree_sitter_cpp(),
                resourceDirectory: "cpp",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .css,
                displayName: "CSS",
                aliases: [],
                fileExtensions: ["css"],
                filenames: [],
                treeSitterLanguage: tree_sitter_css(),
                resourceDirectory: "css",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .dockerfile,
                displayName: "Dockerfile",
                aliases: ["docker"],
                fileExtensions: [],
                filenames: ["Containerfile", "Dockerfile"],
                treeSitterLanguage: tree_sitter_dockerfile(),
                resourceDirectory: "dockerfile",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .dotenv,
                displayName: "dotenv",
                aliases: ["env"],
                fileExtensions: ["env"],
                filenames: [
                    ".env", ".env.development", ".env.example", ".env.local", ".env.production",
                    ".env.test",
                ],
                treeSitterLanguage: tree_sitter_dotenv(),
                resourceDirectory: "dotenv",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .go,
                displayName: "Go",
                aliases: ["golang"],
                fileExtensions: ["go"],
                filenames: [],
                treeSitterLanguage: tree_sitter_go(),
                resourceDirectory: "go",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .graphql,
                displayName: "GraphQL",
                aliases: ["gql"],
                fileExtensions: ["gql", "graphql", "graphqls"],
                filenames: [],
                treeSitterLanguage: tree_sitter_graphql(),
                resourceDirectory: "graphql",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .groovy,
                displayName: "Groovy",
                aliases: [],
                fileExtensions: ["gradle", "groovy", "gsh", "gvy", "gy"],
                filenames: [],
                treeSitterLanguage: tree_sitter_groovy(),
                resourceDirectory: "groovy",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .html,
                displayName: "HTML",
                aliases: ["htm"],
                fileExtensions: ["htm", "html", "xhtml"],
                filenames: [],
                treeSitterLanguage: tree_sitter_html(),
                resourceDirectory: "html",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .java,
                displayName: "Java",
                aliases: [],
                fileExtensions: ["java"],
                filenames: [],
                treeSitterLanguage: tree_sitter_java(),
                resourceDirectory: "java",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .javascript,
                displayName: "JavaScript",
                aliases: ["js", "jsx", "node"],
                fileExtensions: ["cjs", "js", "jsx", "mjs"],
                filenames: [],
                treeSitterLanguage: tree_sitter_javascript(),
                resourceDirectory: "javascript",
                highlightsQueries: [
                    "highlights.scm", "highlights-jsx.scm", "highlights-params.scm",
                ],
                injectionsQueries: ["injections.scm"],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .jsdoc,
                displayName: "JSDoc",
                aliases: ["js-doc"],
                fileExtensions: [],
                filenames: [],
                treeSitterLanguage: tree_sitter_jsdoc(),
                resourceDirectory: "jsdoc",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .json,
                displayName: "JSON",
                aliases: [],
                fileExtensions: ["geojson", "json"],
                filenames: ["Package.resolved"],
                treeSitterLanguage: tree_sitter_json(),
                resourceDirectory: "json",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .json5,
                displayName: "JSON5",
                aliases: ["jsonc"],
                fileExtensions: ["json5", "jsonc"],
                filenames: ["jsconfig.json", "tsconfig.json"],
                treeSitterLanguage: tree_sitter_json5(),
                resourceDirectory: "json5",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .kotlin,
                displayName: "Kotlin",
                aliases: ["kt", "kts"],
                fileExtensions: ["kt", "kts"],
                filenames: [],
                treeSitterLanguage: tree_sitter_kotlin(),
                resourceDirectory: "kotlin",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .markdown,
                displayName: "Markdown",
                aliases: ["md"],
                fileExtensions: ["markdown", "md", "mdown", "mkd", "mkdn"],
                filenames: [],
                treeSitterLanguage: tree_sitter_markdown(),
                resourceDirectory: "markdown",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .markdownInline,
                displayName: "Markdown Inline",
                aliases: ["markdown_inline"],
                fileExtensions: [],
                filenames: [],
                treeSitterLanguage: tree_sitter_markdown_inline(),
                resourceDirectory: "markdown-inline",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .mdx,
                displayName: "MDX",
                aliases: [],
                fileExtensions: ["mdx"],
                filenames: [],
                treeSitterLanguage: tree_sitter_mdx(),
                resourceDirectory: "mdx",
                highlightsQueries: [
                    "highlights.scm", "highlights-jsx.scm", "highlights-params.scm",
                ],
                injectionsQueries: ["injections.scm"],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .objectiveC,
                displayName: "Objective-C",
                aliases: ["obj-c", "objc"],
                fileExtensions: ["m", "mm"],
                filenames: [],
                treeSitterLanguage: tree_sitter_objc(),
                resourceDirectory: "objective-c",
                highlightsQueries: ["highlights-c.scm", "highlights-objective-c.scm"],
                injectionsQueries: [],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .properties,
                displayName: "Java Properties",
                aliases: ["java-properties"],
                fileExtensions: ["properties"],
                filenames: [],
                treeSitterLanguage: tree_sitter_properties(),
                resourceDirectory: "properties",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .python,
                displayName: "Python",
                aliases: ["py"],
                fileExtensions: ["py", "pyi", "pyw"],
                filenames: [],
                treeSitterLanguage: tree_sitter_python(),
                resourceDirectory: "python",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .regex,
                displayName: "Regular Expression",
                aliases: ["regexp"],
                fileExtensions: [],
                filenames: [],
                treeSitterLanguage: tree_sitter_regex(),
                resourceDirectory: "regex",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .ruby,
                displayName: "Ruby",
                aliases: ["rb"],
                fileExtensions: ["gemspec", "podspec", "rake", "rb"],
                filenames: ["Brewfile", "Fastfile", "Gemfile", "Podfile", "Rakefile"],
                treeSitterLanguage: tree_sitter_ruby(),
                resourceDirectory: "ruby",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .rust,
                displayName: "Rust",
                aliases: ["rs"],
                fileExtensions: ["rs"],
                filenames: [],
                treeSitterLanguage: tree_sitter_rust(),
                resourceDirectory: "rust",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .scss,
                displayName: "SCSS",
                aliases: [],
                fileExtensions: ["scss"],
                filenames: [],
                treeSitterLanguage: tree_sitter_scss(),
                resourceDirectory: "scss",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .sql,
                displayName: "SQL",
                aliases: [],
                fileExtensions: ["sql"],
                filenames: [],
                treeSitterLanguage: tree_sitter_sql(),
                resourceDirectory: "sql",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .svelte,
                displayName: "Svelte",
                aliases: [],
                fileExtensions: ["svelte"],
                filenames: [],
                treeSitterLanguage: tree_sitter_svelte(),
                resourceDirectory: "svelte",
                highlightsQueries: ["highlights-html.scm", "highlights-svelte.scm"],
                injectionsQueries: ["injections-html.scm", "injections-svelte.scm"],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .swift,
                displayName: "Swift",
                aliases: ["swiftlang"],
                fileExtensions: ["swift"],
                filenames: [],
                treeSitterLanguage: tree_sitter_swift(),
                resourceDirectory: "swift",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: 47
            ),
            BundledLanguageDefinition(
                id: .toml,
                displayName: "TOML",
                aliases: [],
                fileExtensions: ["toml"],
                filenames: [],
                treeSitterLanguage: tree_sitter_toml(),
                resourceDirectory: "toml",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .tsx,
                displayName: "TSX",
                aliases: ["react-typescript"],
                fileExtensions: ["tsx"],
                filenames: [],
                treeSitterLanguage: tree_sitter_tsx(),
                resourceDirectory: "tsx",
                highlightsQueries: [
                    "highlights-typescript.scm", "highlights-jsx.scm", "highlights-javascript.scm",
                ],
                injectionsQueries: ["injections.scm"],
                localsQueries: ["locals.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .typescript,
                displayName: "TypeScript",
                aliases: ["ts"],
                fileExtensions: ["cts", "mts", "ts"],
                filenames: [],
                treeSitterLanguage: tree_sitter_typescript(),
                resourceDirectory: "typescript",
                highlightsQueries: ["highlights-typescript.scm", "highlights-javascript.scm"],
                injectionsQueries: ["injections.scm"],
                localsQueries: ["locals-typescript.scm", "locals-javascript.scm"],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .vue,
                displayName: "Vue",
                aliases: [],
                fileExtensions: ["vue"],
                filenames: [],
                treeSitterLanguage: tree_sitter_vue(),
                resourceDirectory: "vue",
                highlightsQueries: ["highlights-html.scm", "highlights-vue.scm"],
                injectionsQueries: ["injections-html.scm", "injections-vue.scm"],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .xml,
                displayName: "XML",
                aliases: [],
                fileExtensions: ["plist", "storyboard", "svg", "xib", "xml"],
                filenames: [],
                treeSitterLanguage: tree_sitter_xml(),
                resourceDirectory: "xml",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
            BundledLanguageDefinition(
                id: .yaml,
                displayName: "YAML",
                aliases: ["yml"],
                fileExtensions: ["yaml", "yml"],
                filenames: ["Podfile.lock"],
                treeSitterLanguage: tree_sitter_yaml(),
                resourceDirectory: "yaml",
                highlightsQueries: ["highlights.scm"],
                injectionsQueries: [],
                localsQueries: [],
                injectionTriggerByte: nil
            ),
        ]
        var languages: [HighlightLanguage] = []
        languages.reserveCapacity(definitions.count)
        for definition in definitions {
            languages.append(try makeLanguage(definition))
        }
        return try Self(languages: languages)
    }

    /// Creates one public language definition from bundled metadata.
    ///
    /// - Parameter definition: The generated parser and resource metadata.
    /// - Returns: A validated public language definition.
    /// - Throws: ``HighlighterError`` when a parser or query is invalid.
    private static func makeLanguage(
        _ definition: BundledLanguageDefinition
    ) throws(HighlighterError) -> HighlightLanguage {
        try HighlightLanguage(
            id: definition.id,
            displayName: definition.displayName,
            aliases: definition.aliases,
            fileExtensions: definition.fileExtensions,
            filenames: definition.filenames,
            treeSitterLanguage: definition.treeSitterLanguage,
            highlightsQuery: try query(
                files: definition.highlightsQueries,
                directory: definition.resourceDirectory
            ),
            injectionsQuery: try optionalQuery(
                files: definition.injectionsQueries,
                directory: definition.resourceDirectory
            ),
            localsQuery: try optionalQuery(
                files: definition.localsQueries,
                directory: definition.resourceDirectory
            ),
            injectionTriggerByte: definition.injectionTriggerByte
        )
    }

    /// Concatenates query fragments in their upstream declaration order.
    ///
    /// - Parameters:
    ///   - files: The query filenames to load.
    ///   - directory: The language directory inside package resources.
    /// - Returns: One query source containing every requested fragment.
    /// - Throws: ``HighlighterError`` when a resource cannot be loaded.
    private static func query(
        files: [String],
        directory: String
    ) throws(HighlighterError) -> String {
        var sources: [String] = []
        sources.reserveCapacity(files.count)
        for filename in files {
            sources.append(try resource(filename: filename, directory: directory))
        }
        return sources.joined(separator: "\n")
    }

    /// Loads an optional query only when the language declares fragments.
    ///
    /// - Parameters:
    ///   - files: The query filenames to load.
    ///   - directory: The language directory inside package resources.
    /// - Returns: A combined query, or `nil` when no files were declared.
    /// - Throws: ``HighlighterError`` when a resource cannot be loaded.
    private static func optionalQuery(
        files: [String],
        directory: String
    ) throws(HighlighterError) -> String? {
        guard !files.isEmpty else {
            return nil
        }
        return try query(files: files, directory: directory)
    }

    /// Loads one UTF-8 query resource from the package bundle.
    ///
    /// - Parameters:
    ///   - filename: The complete query filename.
    ///   - directory: The language directory inside package resources.
    /// - Returns: The decoded UTF-8 query source.
    /// - Throws: ``HighlighterError`` when the resource cannot be loaded.
    private static func resource(
        filename: String,
        directory: String
    ) throws(HighlighterError) -> String {
        let subdirectory = "Languages/\(directory)"
        let resourceName = (filename as NSString).deletingPathExtension
        let fileExtension = (filename as NSString).pathExtension
        guard
            let url = Bundle.module.url(
                forResource: resourceName,
                withExtension: fileExtension,
                subdirectory: subdirectory
            )
        else {
            throw HighlighterError.missingResource(
                "\(subdirectory)/\(filename)"
            )
        }
        do {
            return String(decoding: try Data(contentsOf: url), as: UTF8.self)
        } catch {
            throw HighlighterError.unreadableResource(
                resource: "\(subdirectory)/\(filename)",
                message: String(describing: error)
            )
        }
    }
}

/// Stores generated metadata for one bundled language.
private struct BundledLanguageDefinition {
    /// Holds the canonical identifier exposed by the public catalog.
    let id: LanguageID

    /// Holds the human-readable language name.
    let displayName: String

    /// Holds alternate identifiers accepted by catalog lookup.
    let aliases: Set<LanguageID>

    /// Holds normalized file extensions associated with the language.
    let fileExtensions: Set<String>

    /// Holds normalized filenames associated with the language.
    let filenames: Set<String>

    /// Holds the process-lifetime pointer exported by the generated parser.
    let treeSitterLanguage: OpaquePointer?

    /// Holds the resource subdirectory containing matching queries.
    let resourceDirectory: String

    /// Holds highlight query fragments in concatenation order.
    let highlightsQueries: [String]

    /// Holds injection query fragments in concatenation order.
    let injectionsQueries: [String]

    /// Holds locals query fragments in concatenation order.
    let localsQueries: [String]

    /// Holds a byte required by every possible injection match.
    let injectionTriggerByte: UInt8?

    /// Creates generated metadata for one bundled language.
    ///
    /// - Parameters:
    ///   - id: The canonical public language identifier.
    ///   - displayName: The human-readable language name.
    ///   - aliases: Alternate identifiers accepted by the catalog.
    ///   - fileExtensions: File extensions associated with the language.
    ///   - filenames: Complete filenames associated with the language.
    ///   - treeSitterLanguage: The generated parser pointer.
    ///   - resourceDirectory: The directory containing matching queries.
    ///   - highlightsQueries: Highlight query fragments in load order.
    ///   - injectionsQueries: Injection query fragments in load order.
    ///   - localsQueries: Locals query fragments in load order.
    ///   - injectionTriggerByte: A byte required by every injection match.
    init(
        id: LanguageID,
        displayName: String,
        aliases: Set<LanguageID>,
        fileExtensions: Set<String>,
        filenames: Set<String>,
        treeSitterLanguage: OpaquePointer?,
        resourceDirectory: String,
        highlightsQueries: [String],
        injectionsQueries: [String],
        localsQueries: [String],
        injectionTriggerByte: UInt8?
    ) {
        self.id = id
        self.displayName = displayName
        self.aliases = aliases
        self.fileExtensions = fileExtensions
        self.filenames = filenames
        self.treeSitterLanguage = treeSitterLanguage
        self.resourceDirectory = resourceDirectory
        self.highlightsQueries = highlightsQueries
        self.injectionsQueries = injectionsQueries
        self.localsQueries = localsQueries
        self.injectionTriggerByte = injectionTriggerByte
    }
}
