#!/usr/bin/env python3
"""Generates deterministic Swift fixtures shared by comparison runtimes."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


# The repository root contains both the generator and benchmark packages.
REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

# Generated files stay in ignored build output unless another path is given.
DEFAULT_OUTPUT_DIRECTORY = (
    REPOSITORY_ROOT / "Benchmarks" / "Comparison" / ".build" / "fixtures"
)

# A format version makes incompatible manifest changes fail explicitly.
SCHEMA_VERSION = 1

# The original marker appears near the beginning of every generated source.
REVISION_MARKER = "1000"

# The replacement preserves UTF-8 and UTF-16 length during editor benchmarks.
REPLACEMENT_MARKER = "2000"

# These source sizes keep slower competitors measurable on developer hardware.
FIXTURE_SIZES = (
    ("4KiB", "swift-4kib.swift", 4 * 1_024),
    ("64KiB", "swift-64kib.swift", 64 * 1_024),
    ("256KiB", "swift-256kib.swift", 256 * 1_024),
)


def generate_swift_source(minimum_utf16_length: int) -> str:
    """Returns valid ASCII Swift source at or above the requested length."""
    source = (
        "import Foundation\n\n"
        f"let revisionMarker = {REVISION_MARKER}\n\n"
    )
    index = 0
    while len(source) < minimum_utf16_length:
        source += (
            f"struct Model{index}: Codable, Sendable {{\n"
            f"    let identifier: Int = {index}\n"
            f'    let title: String = "Item {index}"\n\n'
            "    func displayTitle() -> String {\n"
            '        "\\(identifier): \\(title)"\n'
            "    }\n"
            "}\n\n"
        )
        index += 1
    return source


def fixture_metadata(
    name: str,
    file_name: str,
    minimum_utf16_length: int,
    source: str,
) -> dict[str, Any]:
    """Returns integrity metadata for one generated source document."""
    encoded_source = source.encode("utf-8")
    return {
        "name": name,
        "fileName": file_name,
        "minimumUTF16Length": minimum_utf16_length,
        "byteCount": len(encoded_source),
        "utf16Count": len(source.encode("utf-16-le")) // 2,
        "lineCount": source.count("\n") + 1,
        "sha256": hashlib.sha256(encoded_source).hexdigest(),
    }


def write_if_changed(path: Path, contents: bytes) -> None:
    """Writes generated bytes only when their on-disk value has changed."""
    if path.exists() and path.read_bytes() == contents:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(contents)


def generate_fixtures(output_directory: Path) -> dict[str, Any]:
    """Generates every source file and returns their shared manifest."""
    fixtures: list[dict[str, Any]] = []
    for name, file_name, minimum_utf16_length in FIXTURE_SIZES:
        source = generate_swift_source(minimum_utf16_length)
        encoded_source = source.encode("utf-8")
        write_if_changed(output_directory / file_name, encoded_source)
        fixtures.append(
            fixture_metadata(
                name,
                file_name,
                minimum_utf16_length,
                source,
            )
        )

    manifest = {
        "schemaVersion": SCHEMA_VERSION,
        "language": "swift",
        "revisionMarker": REVISION_MARKER,
        "replacementMarker": REPLACEMENT_MARKER,
        "fixtures": fixtures,
    }
    manifest_contents = (
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    write_if_changed(output_directory / "manifest.json", manifest_contents)
    return manifest


def parse_arguments() -> argparse.Namespace:
    """Parses command-line options for the fixture generator."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate deterministic source fixtures for comparison benchmarks."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIRECTORY,
        help="Directory that receives generated fixtures and their manifest.",
    )
    return parser.parse_args()


def main() -> int:
    """Generates the fixture corpus and prints its reproducibility metadata."""
    arguments = parse_arguments()
    manifest = generate_fixtures(arguments.output.resolve())
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
